### ISSUE TITLE
Incompat with LemurFusion

### ISSUE THREAD

**Issue by goldenguy00** [prodzpod/MysticsItems#2]
I hate dictionaries

[Log.log](https://github.com/user-attachments/files/17116675/Log.log)

![image](https://github.com/user-attachments/assets/a898465b-62b0-4074-bb0b-9ec8bfbbcac7)

devoted lemurians have 2 inventories btw, the 2nd one is a derivative of the first and is mainly used for various item tracking mechanics. I'm assuming this error happens because GetComponent only ever returns the first. idk. looks like its just a problem with the way the dictionary is updated. image is related

**Comment by goldenguy00** [comment]
correction: i hate the way people use dictionaries. lemurfusion already patches one mod that does unholy shit with them

**Comment by prodzpod** [comment]
isnt this a problem of GetComponent and not dictionaries
